import type { Rank, CountingSystem, CountingSystemConfig } from "./types"

export const countingSystems: Record<CountingSystem, CountingSystemConfig> = {
  "hi-lo": {
    name: "Hi-Lo",
    description: "Most popular system. Level 1, balanced. Best for beginners.",
    level: 1,
    needsTrueCount: true,
    needsAceSideCount: false,
    values: {
      A: -1,
      "2": 1,
      "3": 1,
      "4": 1,
      "5": 1,
      "6": 1,
      "7": 0,
      "8": 0,
      "9": 0,
      "10": -1,
      J: -1,
      Q: -1,
      K: -1,
    },
  },
  ko: {
    name: "KO (Knock-Out)",
    description: "Unbalanced system, no true count needed. Easiest to learn.",
    level: 1,
    needsTrueCount: false,
    needsAceSideCount: false,
    values: {
      A: -1,
      "2": 1,
      "3": 1,
      "4": 1,
      "5": 1,
      "6": 1,
      "7": 1,
      "8": 0,
      "9": 0,
      "10": -1,
      J: -1,
      Q: -1,
      K: -1,
    },
  },
  "hi-opt-i": {
    name: "Hi-Opt I",
    description: "Level 1, more accurate for playing decisions.",
    level: 1,
    needsTrueCount: true,
    needsAceSideCount: true,
    values: {
      A: 0,
      "2": 0,
      "3": 1,
      "4": 1,
      "5": 1,
      "6": 1,
      "7": 0,
      "8": 0,
      "9": 0,
      "10": -1,
      J: -1,
      Q: -1,
      K: -1,
    },
  },
  "hi-opt-ii": {
    name: "Hi-Opt II",
    description: "Level 2, very powerful but harder to master.",
    level: 2,
    needsTrueCount: true,
    needsAceSideCount: true,
    values: {
      A: 0,
      "2": 1,
      "3": 1,
      "4": 2,
      "5": 2,
      "6": 1,
      "7": 1,
      "8": 0,
      "9": 0,
      "10": -2,
      J: -2,
      Q: -2,
      K: -2,
    },
  },
  zen: {
    name: "Zen Count",
    description: "Level 2, excellent balance of power and difficulty.",
    level: 2,
    needsTrueCount: true,
    needsAceSideCount: false,
    values: {
      A: -1,
      "2": 1,
      "3": 1,
      "4": 2,
      "5": 2,
      "6": 2,
      "7": 1,
      "8": 0,
      "9": 0,
      "10": -2,
      J: -2,
      Q: -2,
      K: -2,
    },
  },
  "omega-ii": {
    name: "Omega II",
    description: "Professional level system, extremely accurate.",
    level: 2,
    needsTrueCount: true,
    needsAceSideCount: true,
    values: {
      A: 0,
      "2": 1,
      "3": 1,
      "4": 2,
      "5": 2,
      "6": 2,
      "7": 1,
      "8": 0,
      "9": -1,
      "10": -2,
      J: -2,
      Q: -2,
      K: -2,
    },
  },
  halves: {
    name: "Halves (Wong Halves)",
    description: "Level 3, most powerful but uses fractions.",
    level: 3,
    needsTrueCount: true,
    needsAceSideCount: true,
    values: {
      A: -1,
      "2": 0.5,
      "3": 1,
      "4": 1,
      "5": 1.5,
      "6": 1,
      "7": 0.5,
      "8": 0,
      "9": -0.5,
      "10": -1,
      J: -1,
      Q: -1,
      K: -1,
    },
  },
}

export function getCardValue(rank: Rank, system: CountingSystem): number {
  return countingSystems[system].values[rank]
}

export function calculateTrueCount(runningCount: number, decksRemaining: number): number {
  if (decksRemaining === 0) return 0
  return Math.round(runningCount / decksRemaining)
}
