export interface CasinoRules {
  id: string
  name: string
  location: string
  region:
    | "Las Vegas Strip"
    | "Downtown Las Vegas"
    | "Off-Strip Las Vegas"
    | "Reno"
    | "Atlantic City"
    | "Florida"
    | "Monaco"
  numberOfDecks: 1 | 2 | 6 | 8
  blackjackPayout: "3:2" | "6:5"
  dealerHitsSoft17: boolean
  doubleDownRules: "any" | "9-11-only"
  doubleAfterSplit: boolean
  resplitAces: boolean
  maxResplitHands: number
  lateSurrender: boolean
  minBet: number
  maxBet: number
  houseEdge: number
  specialRules?: string[]
  description: string
  tableSizes: number[] // Available table sizes (e.g., [5, 6, 7])
  typicalTableSize: number // Most common table size
  tableNotes?: string // Notes about table configuration
}

export const casinos: CasinoRules[] = [
  {
    id: "bellagio",
    name: "Bellagio",
    location: "Las Vegas Strip",
    region: "Las Vegas Strip",
    numberOfDecks: 2,
    blackjackPayout: "3:2",
    dealerHitsSoft17: false,
    doubleDownRules: "any",
    doubleAfterSplit: true,
    resplitAces: true,
    maxResplitHands: 4,
    lateSurrender: true,
    minBet: 100,
    maxBet: 10000,
    houseEdge: 0.3,
    description: "Premium double-deck blackjack in high-limit areas with excellent rules and low house edge.",
    tableSizes: [5, 6, 7],
    typicalTableSize: 6,
    tableNotes: "6-7 spots on main floor; 5-6 in high-limit salons for exclusivity",
  },
  {
    id: "mgm-grand",
    name: "MGM Grand",
    location: "Las Vegas Strip",
    region: "Las Vegas Strip",
    numberOfDecks: 6,
    blackjackPayout: "3:2",
    dealerHitsSoft17: false,
    doubleDownRules: "any",
    doubleAfterSplit: true,
    resplitAces: true,
    maxResplitHands: 4,
    lateSurrender: false,
    minBet: 25,
    maxBet: 5000,
    houseEdge: 0.4,
    specialRules: ["Free Bet Blackjack available"],
    description: "Six-deck games with full double-down rules and variants like Free Bet Blackjack.",
    tableSizes: [5, 6, 7],
    typicalTableSize: 7,
    tableNotes: "7-spot for low-limit ($10-25); 5-spot for whales in high-limit",
  },
  {
    id: "wynn-encore",
    name: "Wynn/Encore",
    location: "Las Vegas Strip",
    region: "Las Vegas Strip",
    numberOfDecks: 6,
    blackjackPayout: "3:2",
    dealerHitsSoft17: false,
    doubleDownRules: "any",
    doubleAfterSplit: true,
    resplitAces: true,
    maxResplitHands: 4,
    lateSurrender: true,
    minBet: 50,
    maxBet: 15000,
    houseEdge: 0.35,
    description: "High-limit six-deck blackjack with surrender and re-split aces in luxury salons.",
    tableSizes: [5, 6],
    typicalTableSize: 5,
    tableNotes: "Mostly 5-spot tables in Salon Privé ($100+ min) to reduce wait times",
  },
  {
    id: "el-cortez",
    name: "El Cortez",
    location: "Downtown Las Vegas",
    region: "Downtown Las Vegas",
    numberOfDecks: 2,
    blackjackPayout: "3:2",
    dealerHitsSoft17: true,
    doubleDownRules: "any",
    doubleAfterSplit: true,
    resplitAces: false,
    maxResplitHands: 2,
    lateSurrender: false,
    minBet: 3,
    maxBet: 500,
    houseEdge: 0.45,
    description: "Affordable double-deck 3:2 blackjack, one of the best low-limit options downtown.",
    tableSizes: [6, 7],
    typicalTableSize: 7,
    tableNotes: "7-spot common for $5-15 low-limits; some 6-spot tables",
  },
  {
    id: "circa",
    name: "Circa",
    location: "Downtown Las Vegas",
    region: "Downtown Las Vegas",
    numberOfDecks: 8,
    blackjackPayout: "3:2",
    dealerHitsSoft17: false,
    doubleDownRules: "any",
    doubleAfterSplit: true,
    resplitAces: true,
    maxResplitHands: 4,
    lateSurrender: false,
    minBet: 10,
    maxBet: 2000,
    houseEdge: 0.42,
    specialRules: ["Free Bet Blackjack (dealer pushes on 22)"],
    description: "Mix of games including 3:2 Free Bet Blackjack with free doubles/splits on certain hands.",
    tableSizes: [6, 7],
    typicalTableSize: 7,
    tableNotes: "7-spot standard downtown; 6-spot for some specialty games",
  },
  {
    id: "treasure-island",
    name: "Treasure Island",
    location: "Las Vegas Strip",
    region: "Las Vegas Strip",
    numberOfDecks: 2,
    blackjackPayout: "3:2",
    dealerHitsSoft17: true,
    doubleDownRules: "any",
    doubleAfterSplit: true,
    resplitAces: false,
    maxResplitHands: 2,
    lateSurrender: false,
    minBet: 50,
    maxBet: 3000,
    houseEdge: 0.46,
    description: "Double-deck 3:2 with more affordable minimums than luxury spots on the Strip.",
    tableSizes: [6, 7],
    typicalTableSize: 7,
    tableNotes: "Mix of 6-7 spots; standard Strip configuration",
  },
  {
    id: "south-point",
    name: "South Point",
    location: "Off-Strip, Las Vegas",
    region: "Off-Strip Las Vegas",
    numberOfDecks: 6,
    blackjackPayout: "3:2",
    dealerHitsSoft17: false,
    doubleDownRules: "any",
    doubleAfterSplit: true,
    resplitAces: true,
    maxResplitHands: 4,
    lateSurrender: false,
    minBet: 5,
    maxBet: 1000,
    houseEdge: 0.38,
    description: "Locals-friendly with excellent rules and low table minimums for budget players.",
    tableSizes: [7],
    typicalTableSize: 7,
    tableNotes: "Locals casino - all 7-spot tables for budget play ($5-15 mins)",
  },
  {
    id: "plaza",
    name: "Plaza",
    location: "Downtown Las Vegas",
    region: "Downtown Las Vegas",
    numberOfDecks: 2,
    blackjackPayout: "3:2",
    dealerHitsSoft17: true,
    doubleDownRules: "any",
    doubleAfterSplit: true,
    resplitAces: false,
    maxResplitHands: 2,
    lateSurrender: false,
    minBet: 10,
    maxBet: 1000,
    houseEdge: 0.46,
    description: "Double-deck and six-deck 3:2 games with strong value in downtown Las Vegas.",
    tableSizes: [6, 7],
    typicalTableSize: 7,
    tableNotes: "7-spot downtown standard; some 6-spot tables",
  },
  {
    id: "seminole-hard-rock",
    name: "Seminole Hard Rock Hotel & Casino",
    location: "Hollywood, FL",
    region: "Florida",
    numberOfDecks: 8,
    blackjackPayout: "3:2",
    dealerHitsSoft17: false,
    doubleDownRules: "any",
    doubleAfterSplit: true,
    resplitAces: true,
    maxResplitHands: 3,
    lateSurrender: true,
    minBet: 10,
    maxBet: 5000,
    houseEdge: 0.4,
    description: "Eight-deck blackjack with excellent rules, one of the few live table spots in Florida.",
    tableSizes: [7],
    typicalTableSize: 7,
    tableNotes: "7-spot for 6-8 deck games ($10-25 mins)",
  },
  {
    id: "seminole-classic",
    name: "Seminole Classic Casino",
    location: "Hollywood, FL",
    region: "Florida",
    numberOfDecks: 6,
    blackjackPayout: "3:2",
    dealerHitsSoft17: true,
    doubleDownRules: "any",
    doubleAfterSplit: true,
    resplitAces: true,
    maxResplitHands: 4,
    lateSurrender: false,
    minBet: 10,
    maxBet: 2000,
    houseEdge: 0.5,
    description: "Six-to-eight-deck games with solid mid-stakes options and lower crowds.",
    tableSizes: [7],
    typicalTableSize: 7,
    tableNotes: "Standard 7-spot tables throughout",
  },
  {
    id: "peppermill",
    name: "Peppermill Resort Spa Casino",
    location: "Reno, NV",
    region: "Reno",
    numberOfDecks: 2,
    blackjackPayout: "3:2",
    dealerHitsSoft17: true,
    doubleDownRules: "any",
    doubleAfterSplit: true,
    resplitAces: false,
    maxResplitHands: 2,
    lateSurrender: false,
    minBet: 10,
    maxBet: 1500,
    houseEdge: 0.45,
    description: "Double-deck 3:2 blackjack voted Reno's best with friendly dealers and variety.",
    tableSizes: [6, 7],
    typicalTableSize: 6,
    tableNotes: "6-7 spots; voted best tables in Reno",
  },
  {
    id: "atlantis",
    name: "Atlantis Casino Resort Spa",
    location: "Reno, NV",
    region: "Reno",
    numberOfDecks: 2,
    blackjackPayout: "3:2",
    dealerHitsSoft17: true,
    doubleDownRules: "any",
    doubleAfterSplit: true,
    resplitAces: true,
    maxResplitHands: 4,
    lateSurrender: false,
    minBet: 10,
    maxBet: 2000,
    houseEdge: 0.3,
    specialRules: ["Anything Goes single-deck variant", "Royal Match side bet"],
    description: "Single- and double-deck 3:2 with liberal rules, best blackjack in Reno.",
    tableSizes: [6, 7],
    typicalTableSize: 7,
    tableNotes: "6-7 spots; renowned for best blackjack rules in Reno",
  },
  {
    id: "grand-sierra",
    name: "Grand Sierra Resort",
    location: "Reno, NV",
    region: "Reno",
    numberOfDecks: 6,
    blackjackPayout: "3:2",
    dealerHitsSoft17: false,
    doubleDownRules: "any",
    doubleAfterSplit: true,
    resplitAces: true,
    maxResplitHands: 4,
    lateSurrender: false,
    minBet: 10,
    maxBet: 2000,
    houseEdge: 0.4,
    specialRules: ["Free Bonus Blackjack (free doubles/splits on 9-11)", "Lucky Lucky side bet"],
    description: "Six-deck 3:2 in Reno's largest casino with side wagers for added excitement.",
    tableSizes: [6, 7],
    typicalTableSize: 7,
    tableNotes: "Largest casino in Reno; 6-7 spot tables",
  },
  {
    id: "borgata",
    name: "Borgata Hotel Casino & Spa",
    location: "Atlantic City, NJ",
    region: "Atlantic City",
    numberOfDecks: 8,
    blackjackPayout: "3:2",
    dealerHitsSoft17: false,
    doubleDownRules: "any",
    doubleAfterSplit: true,
    resplitAces: true,
    maxResplitHands: 4,
    lateSurrender: true,
    minBet: 15,
    maxBet: 5000,
    houseEdge: 0.35,
    specialRules: ["Infinite Blackjack live options"],
    description: "Top-rated Atlantic City casino with variety including Infinite Blackjack.",
    tableSizes: [6, 7],
    typicalTableSize: 7,
    tableNotes: "Full 7-player pits for 8-deck; some 6-spot in high-limit",
  },
  {
    id: "ocean-casino",
    name: "Ocean Casino Resort",
    location: "Atlantic City, NJ",
    region: "Atlantic City",
    numberOfDecks: 8,
    blackjackPayout: "3:2",
    dealerHitsSoft17: false,
    doubleDownRules: "any",
    doubleAfterSplit: true,
    resplitAces: true,
    maxResplitHands: 3,
    lateSurrender: true,
    minBet: 10,
    maxBet: 3000,
    houseEdge: 0.4,
    description: "Standard eight-deck with excellent rules at $25+ tables and beachfront vibe.",
    tableSizes: [6, 7],
    typicalTableSize: 7,
    tableNotes: "7-spot dominant; 6-spot for beachfront vibe tables",
  },
  {
    id: "tropicana-ac",
    name: "Tropicana Atlantic City",
    location: "Atlantic City, NJ",
    region: "Atlantic City",
    numberOfDecks: 6,
    blackjackPayout: "3:2",
    dealerHitsSoft17: true,
    doubleDownRules: "any",
    doubleAfterSplit: true,
    resplitAces: false,
    maxResplitHands: 2,
    lateSurrender: true,
    minBet: 10,
    maxBet: 2000,
    houseEdge: 0.45,
    specialRules: ["Spanish 21 variant available"],
    description: "Six-to-eight-deck 3:2 games good for budget players with Spanish 21 variant.",
    tableSizes: [6, 7],
    typicalTableSize: 7,
    tableNotes: "Mix of 6-7 spots; budget-friendly",
  },
  {
    id: "monte-carlo",
    name: "Casino de Monte-Carlo",
    location: "Monaco",
    region: "Monaco",
    numberOfDecks: 6,
    blackjackPayout: "3:2",
    dealerHitsSoft17: false,
    doubleDownRules: "9-11-only",
    doubleAfterSplit: false,
    resplitAces: false,
    maxResplitHands: 2,
    lateSurrender: false,
    minBet: 11,
    maxBet: 10000,
    houseEdge: 0.6,
    specialRules: ["European rules", "Strict dress code required"],
    description: "Six-deck European blackjack in elegant high-society setting with traditional rules.",
    tableSizes: [5, 6, 7],
    typicalTableSize: 6,
    tableNotes: "Elegant European setting; various table sizes for exclusivity",
  },
  {
    id: "sun-monaco",
    name: "Sun Casino",
    location: "Monaco",
    region: "Monaco",
    numberOfDecks: 6,
    blackjackPayout: "3:2",
    dealerHitsSoft17: true,
    doubleDownRules: "any",
    doubleAfterSplit: true,
    resplitAces: true,
    maxResplitHands: 2,
    lateSurrender: false,
    minBet: 11,
    maxBet: 3000,
    houseEdge: 0.5,
    description: "American-style six-deck 3:2 more casual than Monte-Carlo with mixed rules.",
    tableSizes: [6, 7],
    typicalTableSize: 7,
    tableNotes: "More casual European venue; standard table sizes",
  },
  {
    id: "silverton",
    name: "Silverton Casino Lodge",
    location: "Las Vegas, off-Strip",
    region: "Off-Strip Las Vegas",
    numberOfDecks: 2,
    blackjackPayout: "3:2",
    dealerHitsSoft17: true,
    doubleDownRules: "any",
    doubleAfterSplit: true,
    resplitAces: true,
    maxResplitHands: 4,
    lateSurrender: false,
    minBet: 15,
    maxBet: 1000,
    houseEdge: 0.5,
    description: "Locals favorite double-deck 3:2 with low minimums and bass fishing theme.",
    tableSizes: [7],
    typicalTableSize: 7,
    tableNotes: "Locals casino - all 7-spot budget tables",
  },
  {
    id: "palms",
    name: "Palms Casino Resort",
    location: "Las Vegas, off-Strip",
    region: "Off-Strip Las Vegas",
    numberOfDecks: 6,
    blackjackPayout: "3:2",
    dealerHitsSoft17: false,
    doubleDownRules: "any",
    doubleAfterSplit: true,
    resplitAces: true,
    maxResplitHands: 4,
    lateSurrender: true,
    minBet: 5,
    maxBet: 5000,
    houseEdge: 0.3,
    description: "Six-deck 3:2 with all tables now 3:2, great value with high-limit salons.",
    tableSizes: [6, 7],
    typicalTableSize: 7,
    tableNotes: "7-spot main floor; 6-spot high-limit salons ($100+)",
  },
  {
    id: "westgate",
    name: "Westgate Las Vegas",
    location: "Las Vegas Strip",
    region: "Las Vegas Strip",
    numberOfDecks: 6,
    blackjackPayout: "3:2",
    dealerHitsSoft17: false,
    doubleDownRules: "any",
    doubleAfterSplit: true,
    resplitAces: true,
    maxResplitHands: 4,
    lateSurrender: false,
    minBet: 5,
    maxBet: 1000,
    houseEdge: 0.42,
    description: "Explicitly 7-player tables across single/double/multi-deck games with wide bet limits.",
    tableSizes: [7],
    typicalTableSize: 7,
    tableNotes: "All 7-player tables ($5-$1,000 limits)",
  },
]
